global:
  random_state: 42

classification:
  test_size: 0.2
  scoring: accuracy
  gridsearch:
    cv: 5
    n_jobs: -1
    verbose: 1
    params:
      clf__n_estimators: [200, 400]
      clf__max_depth: [null, 15, 30]
      clf__min_samples_split: [2, 5]
      clf__min_samples_leaf: [1, 3]

clustering:
  k_range: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  default_k: 4

regression:
  test_size: 0.2
  metrics: [mae, rmse]
  models:
    random_forest:
      n_estimators: 300
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
